### ISSUE TITLE
Thread reduction

### ISSUE THREAD

**Issue by TilmanG** [Igutech/FTC-2016_New#4]
I'm not quite sure how many we are using but we're running many threads. The overall consensus on the FTC forum is to avoid threads as much as possible unless it's absolutely unavoidable. If we do need threads, we should include idle() functions in order to allow other threads to catch up and not hog resources

**Comment by kev626** [comment]
After evaluation, I am closing this because we use calls to Thread.sleep() (responsibly) which allows scheduling of when threads should trade off CPU time. Our threads automatically terminate when the program ends as well, preventing any movement, crashes, null pointers, etc. The idle() call is essentially equal to a Thread.sleep, but it does not specify a time the Thread should be available to switch back to, and therefore you can control less.
